printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quotePropts: as-needed
jsxSingleQuote: false
trailingComma: "all"
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: "always"
#---
insertPragma: false
proseWrap: "preserve"
endOfLine: "lf"
